version: '3'
services:
  pg:
    image: postgres:16.4-alpine3.20
    container_name: pg-tessera
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tessera
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0-alpine3.20
    container_name: redis-tessera
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redisdata:/data

  tessera:
    build: .
    container_name: tessera
    ports:
      - '3000:3000'
    depends_on:
      - pg
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@pg:5432/tessera?schema=public
      REDIS_URL: redis://redis:6379
      JWT_SECRET: tessera-secret
      MAX_EXPIRES_DIFF_IN_MINUTES: 5
      PORT: 3000
