version: '3'
services:
  pg:
    image: postgres:16.4-alpine3.20
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tessera
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data

  tessera:
    build: .
    ports:
      - '8080:3000'
    depends_on:
      - pg
    environment:
      DATABASE_URL: postgres://postgres:postgres@pg:5432/tessera?schema=public
      JWT_SECRET: tessera-secret
      PORT: 3000
